[[FreeBSDSysroot]]
arch = "aarch64"
git-tree-sha1 = "29e56801417b12b64cf235a70f57de93a054cf74"
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot.download]]
    sha256 = "69a047160b3d8466fc826fa7b4435d711227620fa5e24e9c46b169603ead27b2"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-v14.1.0-aarch64-unknown-freebsd14.1.tar.gz"
[[FreeBSDSysroot]]
arch = "x86_64"
git-tree-sha1 = "812bac0635fbdaa835d59b25a1022f606f74d9dc"
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot.download]]
    sha256 = "c422a3025cdfad6146bb68f0bf78d7318cec6f9985fb9afb4978f083898efca8"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-v14.1.0-x86_64-unknown-freebsd14.1.tar.gz"

[[FreeBSDSysroot-build_log]]
arch = "aarch64"
git-tree-sha1 = "e16210c63dcca1e0d4257141159d7d911cc50212"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-build_log.download]]
    sha256 = "cfb152f0d99736023313a58b96c573855aa7b715615378fcabb0c94abdbd47cf"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-build_log-v14.1.0-aarch64-unknown-freebsd14.1.tar.gz"
[[FreeBSDSysroot-build_log]]
arch = "x86_64"
git-tree-sha1 = "954ea51d30a78324063123c4b4efe4fc8068d547"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-build_log.download]]
    sha256 = "d1a356d6c047b46ef9ca5a233b161bb6e612eae0613721b9ced00b1588edfcaf"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-build_log-v14.1.0-x86_64-unknown-freebsd14.1.tar.gz"

[[FreeBSDSysroot-extract_log]]
arch = "aarch64"
git-tree-sha1 = "dd80e2036ec172eca336aacd042e7a6ae0512c8e"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-extract_log.download]]
    sha256 = "b742038d86ddbad50f6e366b3a629fe87f1662604e952b69677951d9d3156cc0"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-extract_log-v14.1.0-aarch64-unknown-freebsd14.1.tar.gz"
[[FreeBSDSysroot-extract_log]]
arch = "x86_64"
git-tree-sha1 = "a2be38753c05603ed99b5cf02f745ea4737c68cc"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-extract_log.download]]
    sha256 = "8990abdcedee64b55f327ccb768a24dc6a32412032b4ae5918dc5071f56f463d"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-extract_log-v14.1.0-x86_64-unknown-freebsd14.1.tar.gz"
