[[FreeBSDSysroot]]
arch = "aarch64"
git-tree-sha1 = "29e56801417b12b64cf235a70f57de93a054cf74"
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot.download]]
    sha256 = "8bafa5c96ac9eb50029b4e219d10474666648d251a92d98421696b8d895f6411"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-v14.1.0-aarch64-unknown-freebsd14.1.tar.gz"
[[FreeBSDSysroot]]
arch = "x86_64"
git-tree-sha1 = "812bac0635fbdaa835d59b25a1022f606f74d9dc"
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot.download]]
    sha256 = "c468e802285eecac5dea96a20d8ce0e6d3506bbb27cffb0dbd11a461eb3cbee0"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-v14.1.0-x86_64-unknown-freebsd14.1.tar.gz"

[[FreeBSDSysroot-build_log]]
arch = "aarch64"
git-tree-sha1 = "e16210c63dcca1e0d4257141159d7d911cc50212"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-build_log.download]]
    sha256 = "99ab5756ecc88c13d0b01e46a185ef3c217056864cd7e5ba92278784aabee955"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-build_log-v14.1.0-aarch64-unknown-freebsd14.1.tar.gz"
[[FreeBSDSysroot-build_log]]
arch = "x86_64"
git-tree-sha1 = "954ea51d30a78324063123c4b4efe4fc8068d547"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-build_log.download]]
    sha256 = "36230bbf6d6ac0d589395415b33545d2f830e23c03d643b5dadeebce7d3f2533"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-build_log-v14.1.0-x86_64-unknown-freebsd14.1.tar.gz"

[[FreeBSDSysroot-extract_log]]
arch = "aarch64"
git-tree-sha1 = "dd80e2036ec172eca336aacd042e7a6ae0512c8e"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-extract_log.download]]
    sha256 = "02669e88f5e81eddddd3b2f2365ad2006ee1a02f600543b618e329f193721483"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-extract_log-v14.1.0-aarch64-unknown-freebsd14.1.tar.gz"
[[FreeBSDSysroot-extract_log]]
arch = "x86_64"
git-tree-sha1 = "a2be38753c05603ed99b5cf02f745ea4737c68cc"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-extract_log.download]]
    sha256 = "ad0bd3e41a3a29b1aba471abcb3f247117347b4f63237e4f96df72b992f70107"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-extract_log-v14.1.0-x86_64-unknown-freebsd14.1.tar.gz"
