[[FreeBSDSysroot]]
arch = "aarch64"
git-tree-sha1 = "09a190d171058daaa29dcfdcc1364e13fbe96bf3"
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot.download]]
    sha256 = "3606058204822ebba657b6a6a87c0c85d27ec68dffe36ae5dc17ee622084b11a"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-v14.1.0-aarch64-unknown-freebsd14.1.tar.gz"
[[FreeBSDSysroot]]
arch = "x86_64"
git-tree-sha1 = "8ace5f47d5cbf35a012ea99b524bc5f96983b311"
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot.download]]
    sha256 = "0d59e6f19940b25dd4aa933884cc48376daaa3b94424a6153f796930b67cd1d6"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-v14.1.0-x86_64-unknown-freebsd14.1.tar.gz"

[[FreeBSDSysroot-build_log]]
arch = "aarch64"
git-tree-sha1 = "a8233ca2ffe9ca2b3085fa7a05c862348b27ce1b"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-build_log.download]]
    sha256 = "53336e9ba7af0ab6dbcc463537959a33b9eda9d75dd4341bd414e3bd7c9d249c"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-build_log-v14.1.0-aarch64-unknown-freebsd14.1.tar.gz"
[[FreeBSDSysroot-build_log]]
arch = "x86_64"
git-tree-sha1 = "659dc75aaacf1534173ba6a37ae373cb92f200d5"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-build_log.download]]
    sha256 = "8bf25fe7ba20d4f63b4c9f8b2efcc6ce45734d8eabf8449eb2bca3c7d7eb1a9e"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-build_log-v14.1.0-x86_64-unknown-freebsd14.1.tar.gz"

[[FreeBSDSysroot-extract_log]]
arch = "aarch64"
git-tree-sha1 = "f3cef240ca0c8b3511ce1b4f1e2c8fec6ceafb8d"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-extract_log.download]]
    sha256 = "063922d2ae007e389574c529429af95433fc9a35f690a9bb076310f107e83102"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-extract_log-v14.1.0-aarch64-unknown-freebsd14.1.tar.gz"
[[FreeBSDSysroot-extract_log]]
arch = "x86_64"
git-tree-sha1 = "940217b6386d9b93263bcb9b6864aa79371ec461"
lazy = true
os = "freebsd"
os_version = "14.1.0"

    [[FreeBSDSysroot-extract_log.download]]
    sha256 = "b9cf1f74d88f55c1c082398968e3b60c28cf9d4b49509d1749b71587803d8c57"
    url = "https://github.com/staticfloat/FreeBSDSysroot_jll.jl/releases/download/v14.1.0-GCCBootstrap-x86_64-linux-gnu/FreeBSDSysroot-extract_log-v14.1.0-x86_64-unknown-freebsd14.1.tar.gz"
